
// THIS FILE IS GENERATED BY THE `$ arcli icons` command
// DO NOT DIRECTLY EDIT !!!!!!!!!!!!!!!!

import AlertCircle from './svgs/AlertCircle';
import AlertOctagon from './svgs/AlertOctagon';
import AlertTriangle from './svgs/AlertTriangle';
import ArrowDown from './svgs/ArrowDown';
import ArrowDownCircle from './svgs/ArrowDownCircle';
import ArrowDownLeft from './svgs/ArrowDownLeft';
import ArrowDownRight from './svgs/ArrowDownRight';
import ArrowLeft from './svgs/ArrowLeft';
import ArrowLeftCircle from './svgs/ArrowLeftCircle';
import ArrowRight from './svgs/ArrowRight';
import ArrowRightCircle from './svgs/ArrowRightCircle';
import ArrowUp from './svgs/ArrowUp';
import ArrowUpCircle from './svgs/ArrowUpCircle';
import ArrowUpLeft from './svgs/ArrowUpLeft';
import ArrowUpRight from './svgs/ArrowUpRight';
import Box from './svgs/Box';
import Check from './svgs/Check';
import ChevronDown from './svgs/ChevronDown';
import ChevronLeft from './svgs/ChevronLeft';
import ChevronRight from './svgs/ChevronRight';
import ChevronUp from './svgs/ChevronUp';
import Clipboard from './svgs/Clipboard';
import Code from './svgs/Code';
import Copy from './svgs/Copy';
import Cpu from './svgs/Cpu';
import ExternalLink from './svgs/ExternalLink';
import Feather from './svgs/Feather';
import File from './svgs/File';
import Filter from './svgs/Filter';
import Folder from './svgs/Folder';
import Heart from './svgs/Heart';
import HelpCircle from './svgs/HelpCircle';
import Info from './svgs/Info';
import Layout from './svgs/Layout';
import List from './svgs/List';
import Maximize from './svgs/Maximize';
import Menu from './svgs/Menu';
import Minimize from './svgs/Minimize';
import Minus from './svgs/Minus';
import MinusCircle from './svgs/MinusCircle';
import MinusSquare from './svgs/MinusSquare';
import Monitor from './svgs/Monitor';
import MoreHorizontal from './svgs/MoreHorizontal';
import MoreVertical from './svgs/MoreVertical';
import Package from './svgs/Package';
import Plus from './svgs/Plus';
import PlusCircle from './svgs/PlusCircle';
import PlusSquare from './svgs/PlusSquare';
import RefreshCw from './svgs/RefreshCw';
import Settings from './svgs/Settings';
import Sidebar from './svgs/Sidebar';
import Sliders from './svgs/Sliders';
import Tag from './svgs/Tag';
import X from './svgs/X';
import XCircle from './svgs/XCircle';
import XOctagon from './svgs/XOctagon';
import XSquare from './svgs/XSquare';

const icons = {
    AlertCircle,
    AlertOctagon,
    AlertTriangle,
    ArrowDown,
    ArrowDownCircle,
    ArrowDownLeft,
    ArrowDownRight,
    ArrowLeft,
    ArrowLeftCircle,
    ArrowRight,
    ArrowRightCircle,
    ArrowUp,
    ArrowUpCircle,
    ArrowUpLeft,
    ArrowUpRight,
    Box,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Clipboard,
    Code,
    Copy,
    Cpu,
    ExternalLink,
    Feather,
    File,
    Filter,
    Folder,
    Heart,
    HelpCircle,
    Info,
    Layout,
    List,
    Maximize,
    Menu,
    Minimize,
    Minus,
    MinusCircle,
    MinusSquare,
    Monitor,
    MoreHorizontal,
    MoreVertical,
    Package,
    Plus,
    PlusCircle,
    PlusSquare,
    RefreshCw,
    Settings,
    Sidebar,
    Sliders,
    Tag,
    X,
    XCircle,
    XOctagon,
    XSquare,
};

export {
    icons as default,
    AlertCircle,
    AlertOctagon,
    AlertTriangle,
    ArrowDown,
    ArrowDownCircle,
    ArrowDownLeft,
    ArrowDownRight,
    ArrowLeft,
    ArrowLeftCircle,
    ArrowRight,
    ArrowRightCircle,
    ArrowUp,
    ArrowUpCircle,
    ArrowUpLeft,
    ArrowUpRight,
    Box,
    Check,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    Clipboard,
    Code,
    Copy,
    Cpu,
    ExternalLink,
    Feather,
    File,
    Filter,
    Folder,
    Heart,
    HelpCircle,
    Info,
    Layout,
    List,
    Maximize,
    Menu,
    Minimize,
    Minus,
    MinusCircle,
    MinusSquare,
    Monitor,
    MoreHorizontal,
    MoreVertical,
    Package,
    Plus,
    PlusCircle,
    PlusSquare,
    RefreshCw,
    Settings,
    Sidebar,
    Sliders,
    Tag,
    X,
    XCircle,
    XOctagon,
    XSquare,
};
