/**
 * Generated by Reactium
 * DO NOT directly edit this file !!!!!!
 */

module.exports = {
    domains: {
        LoadingSpinner: {
            name: 'LoadingSpinner',
            implied: 'Loading',
            original:
                'reactium_modules/@atomic-reactor/reactium-core/components/Loading/reactium-domain-Loading.js',
        },
        RTKCode: {
            name: 'RTKCode',
            implied: 'Code',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-core/Code/domain.js',
        },
        RTKColorSelect: {
            name: 'RTKColorSelect',
            implied: 'ColorSelect',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-core/ColorSelect/domain.js',
        },
        RTKComponentDemo: {
            name: 'RTKComponentDemo',
            implied: 'ComponentDemo',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-core/ComponentDemo/domain.js',
        },
        RTKContent: {
            name: 'RTKContent',
            implied: 'Content',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-core/Content/domain.js',
        },
        RTKIconFeather: {
            name: 'RTKIconFeather',
            implied: 'Feather',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-core/Icon/Feather/domain.js',
        },
        RTKIcon: {
            name: 'RTKIcon',
            implied: 'Icon',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-core/Icon/domain.js',
        },
        RTKLogo: {
            name: 'RTKLogo',
            implied: 'Logo',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-core/Logo/domain.js',
        },
        RTKMarkdown: {
            name: 'RTKMarkdown',
            implied: 'Markdown',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-core/Markdown/domain.js',
        },
        RTKSidebar: {
            name: 'RTKSidebar',
            implied: 'Sidebar',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-core/Sidebar/domain.js',
        },
        RTKToolbar: {
            name: 'RTKToolbar',
            implied: 'Toolbar',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-core/Toolbar/domain.js',
        },
        RTK: {
            name: 'RTK',
            implied: 'reactium-toolkit-core',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-core/domain.js',
        },
        ToolkitElementAlert: {
            name: 'ToolkitElementAlert',
            reactiumToolkit: { group: { id: 'alert', label: 'Alert' } },
            implied: 'Alert',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-demo/toolkit/Alert/domain.js',
        },
        ToolkitElementBreakpoint: {
            name: 'ToolkitElementBreakpoint',
            reactiumToolkit: {
                group: { id: 'breakpoint', label: 'Breakpoint' },
            },
            implied: 'Breakpoint',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-demo/toolkit/Breakpoint/domain.js',
        },
        ToolkitElementButton: {
            name: 'ToolkitElementButton',
            reactiumToolkit: { group: { id: 'button', label: 'Button' } },
            implied: 'Button',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-demo/toolkit/Button/domain.js',
        },
        ToolkitElementIcon: {
            name: 'ToolkitElementIcon',
            reactiumToolkit: { group: { id: 'icon', label: 'Icon' } },
            implied: 'Icon',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-demo/toolkit/Icon/domain.js',
        },
        ToolkitElementOverview: {
            name: 'ToolkitElementOverview',
            reactiumToolkit: { group: { id: 'overview', label: 'Overview' } },
            implied: 'Overview',
            original:
                'reactium_modules/@atomic-reactor/reactium-toolkit-demo/toolkit/Overview/domain.js',
        },
        RUIColor: {
            name: 'RUIColor',
            implied: 'Colors',
            original:
                'reactium_modules/@atomic-reactor/reactium-ui/Colors/reactium-domain-RUIColors.js',
        },
        RUIIconFeather: {
            name: 'RUIIconFeather',
            implied: 'Feather',
            original:
                'reactium_modules/@atomic-reactor/reactium-ui/Icon/Feather/domain.js',
        },
        RUIIconLinear: {
            name: 'RUIIconLinear',
            implied: 'Linear',
            original:
                'reactium_modules/@atomic-reactor/reactium-ui/Icon/Linear/domain.js',
        },
        RUIIcon: {
            name: 'RUIIcon',
            implied: 'Icon',
            original:
                'reactium_modules/@atomic-reactor/reactium-ui/Icon/domain.js',
        },
        RUIAlert: {
            name: 'RUIAlert',
            implied: 'Alert',
            original:
                'reactium_modules/@atomic-reactor/reactium-ui/RUI/Alert/domain.js',
        },
        RUIBreakpoint: {
            name: 'RUIBreakpoint',
            implied: 'Breakpoint',
            original:
                'reactium_modules/@atomic-reactor/reactium-ui/RUI/Breakpoint/domain.js',
        },
        RUIButton: {
            name: 'RUIButton',
            implied: 'Button',
            original:
                'reactium_modules/@atomic-reactor/reactium-ui/RUI/Button/domain.js',
        },
        RUIForm: {
            name: 'RUIForm',
            implied: 'Form',
            original:
                'reactium_modules/@atomic-reactor/reactium-ui/ReactiumUI/Form/domain.js',
        },
        RUIPortal: {
            name: 'RUIPortal',
            implied: 'Portal',
            original:
                'reactium_modules/@atomic-reactor/reactium-ui/RUI/Portal/domain.js',
        },
        RUIToggle: {
            name: 'RUIToggle',
            implied: 'Toggle',
            original:
                'reactium_modules/@atomic-reactor/reactium-ui/RUI/Toggle/domain.js',
        },
        RUIX: {
            name: 'RUIX',
            implied: 'X',
            original:
                'reactium_modules/@atomic-reactor/reactium-ui/RUI/X/domain.js',
        },
        RUI: {
            name: 'RUI',
            implied: 'RUI',
            original:
                'reactium_modules/@atomic-reactor/reactium-ui/RUI/domain.js',
        },
        RUIHooks: {
            name: 'RUIHooks',
            implied: 'hooks',
            original:
                'reactium_modules/@atomic-reactor/reactium-ui/RUI/hooks/domain.js',
        },
        ReactiumUIAll: {
            name: 'ReactiumUIAll',
            implied: 'reactium-ui',
            original:
                'reactium_modules/@atomic-reactor/reactium-ui/reactium-domain-RUI.js',
        },
    },
    relative: {
        'reactium_modules/@atomic-reactor/reactium-core/components/Loading':
            'LoadingSpinner',
        'reactium_modules/@atomic-reactor/reactium-toolkit-core/Code':
            'RTKCode',
        'reactium_modules/@atomic-reactor/reactium-toolkit-core/ColorSelect':
            'RTKColorSelect',
        'reactium_modules/@atomic-reactor/reactium-toolkit-core/ComponentDemo':
            'RTKComponentDemo',
        'reactium_modules/@atomic-reactor/reactium-toolkit-core/Content':
            'RTKContent',
        'reactium_modules/@atomic-reactor/reactium-toolkit-core/Icon/Feather':
            'RTKIconFeather',
        'reactium_modules/@atomic-reactor/reactium-toolkit-core/Icon':
            'RTKIcon',
        'reactium_modules/@atomic-reactor/reactium-toolkit-core/Logo':
            'RTKLogo',
        'reactium_modules/@atomic-reactor/reactium-toolkit-core/Markdown':
            'RTKMarkdown',
        'reactium_modules/@atomic-reactor/reactium-toolkit-core/Sidebar':
            'RTKSidebar',
        'reactium_modules/@atomic-reactor/reactium-toolkit-core/Toolbar':
            'RTKToolbar',
        'reactium_modules/@atomic-reactor/reactium-toolkit-core': 'RTK',
        'reactium_modules/@atomic-reactor/reactium-toolkit-demo/toolkit/Alert':
            'ToolkitElementAlert',
        'reactium_modules/@atomic-reactor/reactium-toolkit-demo/toolkit/Breakpoint':
            'ToolkitElementBreakpoint',
        'reactium_modules/@atomic-reactor/reactium-toolkit-demo/toolkit/Button':
            'ToolkitElementButton',
        'reactium_modules/@atomic-reactor/reactium-toolkit-demo/toolkit/Icon':
            'ToolkitElementIcon',
        'reactium_modules/@atomic-reactor/reactium-toolkit-demo/toolkit/Overview':
            'ToolkitElementOverview',
        'reactium_modules/@atomic-reactor/reactium-ui/Colors': 'RUIColor',
        'reactium_modules/@atomic-reactor/reactium-ui/Icon/Feather':
            'RUIIconFeather',
        'reactium_modules/@atomic-reactor/reactium-ui/Icon/Linear':
            'RUIIconLinear',
        'reactium_modules/@atomic-reactor/reactium-ui/Icon': 'RUIIcon',
        'reactium_modules/@atomic-reactor/reactium-ui/RUI/Alert': 'RUIAlert',
        'reactium_modules/@atomic-reactor/reactium-ui/RUI/Breakpoint':
            'RUIBreakpoint',
        'reactium_modules/@atomic-reactor/reactium-ui/RUI/Button': 'RUIButton',
        'reactium_modules/@atomic-reactor/reactium-ui/RUI/Form': 'RUIForm',
        'reactium_modules/@atomic-reactor/reactium-ui/RUI/Portal': 'RUIPortal',
        'reactium_modules/@atomic-reactor/reactium-ui/RUI/Toggle': 'RUIToggle',
        'reactium_modules/@atomic-reactor/reactium-ui/RUI/X': 'RUIX',
        'reactium_modules/@atomic-reactor/reactium-ui/RUI': 'RUI',
        'reactium_modules/@atomic-reactor/reactium-ui/RUI/hooks': 'RUIHooks',
        'reactium_modules/@atomic-reactor/reactium-ui/ReactiumUI/Form':
            'RUIForm',
        'reactium_modules/@atomic-reactor/reactium-ui': 'ReactiumUIAll',
    },
};
